-- inventory core provider
local Shim = ...
T.suite('inventory')

local Core = LXRCore.Inventory.CoreLogic

local function offline(weight, slots)
    return { Offline = true, PlayerData = { citizenid = 'INV00001', items = {}, weight = weight or 5000, slots = slots or 5, money = {}, metadata = {} } }
end

T.test('AddItem stacks non-unique, separates unique, respects weight and slots', function()
    local p = offline(5000, 3)
    T.eq(Core.AddItem(p, 'bread', 2), true)
    T.eq(Core.AddItem(p, 'bread', 3), true)
    T.eq(Core.Count(p.PlayerData.items, 'bread'), 5)
    T.eq(#Core.SlotsByItem(p.PlayerData.items, 'bread'), 1, 'stacked in one slot')
    T.eq(Core.AddItem(p, 'id_card', 1), true)
    T.eq(Core.AddItem(p, 'id_card', 1), true)
    T.eq(#Core.SlotsByItem(p.PlayerData.items, 'id_card'), 2, 'unique items never stack')
    local ok, err = Core.AddItem(p, 'water', 1)
    T.eq(ok, false)
    T.eq(err, 'too_heavy', 'no free slot')
    local ok2, err2 = Core.AddItem(p, 'nope', 1)
    T.eq(err2, 'item_not_exist')
    local heavy = offline(1000, 10)
    T.eq(select(2, Core.AddItem(heavy, 'pickaxe', 1)), 'too_heavy', 'weight limit')
    T.eq(select(2, Core.AddItem(heavy, 'bread', 0)), 'invalid_amount')
end)

T.test('weapons receive a serial and quality', function()
    local p = offline(10000, 5)
    T.eq(Core.AddItem(p, 'weapon_revolver_cattleman', 1), true)
    local w = Core.GetItemByName(p.PlayerData.items, 'weapon_revolver_cattleman')
    T.ok(w.info.serie and #w.info.serie == 15, 'serial generated')
    T.eq(w.info.quality, 100)
end)

T.test('RemoveItem is all-or-nothing across stacks', function()
    local p = offline(50000, 10)
    Core.AddItem(p, 'bread', 3, 1)
    Core.AddItem(p, 'bread', 3, 2)
    T.eq(Core.Count(p.PlayerData.items, 'bread'), 6)
    T.eq(Core.RemoveItem(p, 'bread', 7), false, 'more than owned')
    T.eq(Core.Count(p.PlayerData.items, 'bread'), 6, 'untouched after failure')
    T.eq(Core.RemoveItem(p, 'bread', 5), true)
    T.eq(Core.Count(p.PlayerData.items, 'bread'), 1)
    T.eq(Core.RemoveItem(p, 'bread', 1, 2), true, 'remove from explicit slot')
    T.eq(p.PlayerData.items[2], nil)
end)

T.test('Serialize / Deserialize round trip drops unknown items', function()
    local p = offline(50000, 10)
    Core.AddItem(p, 'bread', 2)
    Core.AddItem(p, 'water', 1, nil, { quality = 50 })
    local raw = Core.Serialize(p.PlayerData.items)
    local back = Core.Deserialize(raw)
    T.eq(Core.Count(back, 'bread'), 2)
    T.eq(Core.GetItemByName(back, 'water').info.quality, 50)
    local withUnknown = Core.Deserialize('[{"name":"ghost","amount":1,"slot":1},{"name":"bread","amount":1,"slot":2}]')
    T.eq(withUnknown[1], nil)
    T.eq(withUnknown[2].name, 'bread')
end)

T.test('TotalWeight and free slot', function()
    local p = offline(50000, 3)
    Core.AddItem(p, 'bread', 2)
    T.eq(Core.TotalWeight(p.PlayerData.items), 500)
    T.eq(Core.FirstFreeSlot(p.PlayerData.items, 3), 2)
end)
