LXRShared = LXRShared or {}
LXRShared.Weapons = {
	
	-- Revolvers
	{ model = 'WEAPON_REVOLVER_CATTLEMAN',               name = 'weapon_revolver_cattleman',            attachPoint = 2,    label = 'Colt M1873 Single Action',     weight = 1000,   type = 'weapon',      ammotype = 'AMMO_REVOLVER',        image = 'weapon_revolver01.png',      unique = true,   useable = true,   level = 0,     description = 'Every cowboy has a first. And this revolver will probably be it' },
	{ model = 'WEAPON_REVOLVER_CATTLEMAN_MEXICAN',       name = 'weapon_revolver_cattleman_mexican',    attachPoint = 2,    label = 'Steel Colt M1873',              weight = 1000,   type = 'weapon',      ammotype = 'AMMO_REVOLVER',        image = 'weapon_revolver02.png',      unique = true,   useable = true,   level = 0,     description = 'Every cowboy has a first. And this revolver will probably be it, for the rich cowboys at least' },
	{ model = 'WEAPON_REVOLVER_DOUBLEACTION_GAMBLER',    name = 'weapon_revolver_doubleaction_gambler', attachPoint = 2,    label = 'Colt M1892 Double-action',      weight = 1000,   type = 'weapon',      ammotype = 'AMMO_REVOLVER',        image = 'weapon_revolver03.png',      unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_REVOLVER_SCHOFIELD',               name = 'weapon_revolver_schofield',            attachPoint = 2,    label = 'Smith & Wesson No. 3',          weight = 1000,   type = 'weapon',      ammotype = 'AMMO_REVOLVER',        image = 'weapon_revolver04.png',      unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_REVOLVER_LEMAT',                   name = 'weapon_revolver_lemat',                attachPoint = 2,    label = 'LeMat Revolver',                weight = 1000,   type = 'weapon',      ammotype = 'AMMO_REVOLVER',        image = 'weapon_revolver05.png',      unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_REVOLVER_NAVY',                    name = 'weapon_revolver_navy',                 attachPoint = 2,    label = 'Navy Revolver 1851',            weight = 1000,   type = 'weapon',      ammotype = 'AMMO_REVOLVER',        image = 'weapon_revolver_navy.png',   unique = true,   useable = true,   level = 0,     description = 'Placeholder' },

	-- Pistols
	{ model = 'WEAPON_PISTOL_VOLCANIC',                  name = 'weapon_pistol_volcanic',               attachPoint = 2,    label = 'Volcanic Pistol',               weight = 1000,   type = 'weapon',      ammotype = 'AMMO_PISTOL',          image = 'weapon_pistol01.png',       unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_PISTOL_M1899',                     name = 'weapon_pistol_m1899',                  attachPoint = 2,    label = 'FN Browning M1900',             weight = 1000,   type = 'weapon',      ammotype = 'AMMO_PISTOL',          image = 'weapon_pistol02.png',       unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_PISTOL_MAUSER',                    name = 'weapon_pistol_mauser',                 attachPoint = 2,    label = 'Mauser C96',                    weight = 1000,   type = 'weapon',      ammotype = 'AMMO_PISTOL',          image = 'weapon_pistol03.png',       unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_PISTOL_SEMIAUTO',                  name = 'weapon_pistol_semiauto',               attachPoint = 2,    label = 'Borchardt C-93',                weight = 1000,   type = 'weapon',      ammotype = 'AMMO_PISTOL',          image = 'weapon_pistol04.png',       unique = true,   useable = true,   level = 0,     description = 'Placeholder' },

	-- Repeaters
	{ model = 'WEAPON_REPEATER_CARBINE',                 name = 'weapon_repeater_carbine',              attachPoint = 9,    label = 'Spencer Model 1865',            weight = 1000,   type = 'weapon',      ammotype = 'AMMO_REPEATER',        image = 'weapon_repeater01.png',     unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_REPEATER_WINCHESTER',              name = 'weapon_repeater_winchester',           attachPoint = 9,    label = 'Winchester Model 1866',         weight = 1000,   type = 'weapon',      ammotype = 'AMMO_REPEATER',        image = 'weapon_repeater02.png',     unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_REPEATER_HENRY',                   name = 'weapon_repeater_henry',                attachPoint = 9,    label = 'Henry Model 1860',              weight = 1000,   type = 'weapon',      ammotype = 'AMMO_REPEATER',        image = 'weapon_repeater03.png',     unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_REPEATER_EVANS',                   name = 'weapon_repeater_evans',                attachPoint = 9,    label = 'Evans Repeating Rifle',         weight = 1000,   type = 'weapon',      ammotype = 'AMMO_REPEATER',        image = 'weapon_repeater_evans.png', unique = true,   useable = true,   level = 0,     description = 'Placeholder' },

	-- Rifles
	{ model = 'WEAPON_RIFLE_VARMINT',                    name = 'weapon_rifle_varmint',                 attachPoint = 9,    label = 'Winchester Model 1890',         weight = 1000,   type = 'weapon',      ammotype = 'AMMO_RIFLE',           image = 'weapon_rifle01.png',        unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_RIFLE_SPRINGFIELD',                name = 'weapon_rifle_springfield',             attachPoint = 9,    label = 'Springfield Model 1873',        weight = 1000,   type = 'weapon',      ammotype = 'AMMO_RIFLE',           image = 'weapon_rifle02.png',        unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_RIFLE_BOLTACTION',                 name = 'weapon_rifle_boltaction',              attachPoint = 9,    label = 'Springfield Model 1892',        weight = 1000,   type = 'weapon',      ammotype = 'AMMO_RIFLE',           image = 'weapon_rifle03.png',        unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_RIFLE_ELEPHANT',                   name = 'weapon_rifle_elephant',                attachPoint = 9,    label = 'Elephant Rifle',                weight = 1000,   type = 'weapon',      ammotype = 'AMMO_RIFLE',           image = 'weapon_rifle04.png',        unique = true,   useable = true,   level = 0,     description = 'Placeholder' },

	-- Shotguns
	{ model = 'WEAPON_SHOTGUN_DOUBLEBARREL',             name = 'weapon_shotgun_doublebarrel',          attachPoint = 9,    label = 'Colt Hammer Shotgun 1878',      weight = 1000,   type = 'weapon',      ammotype = 'AMMO_SHOTGUN',         image = 'weapon_shotgun01.png',      unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC',      name = 'weapon_shotgun_doublebarrel_exotic',   attachPoint = 9,    label = 'Steel Hammer Shotgun 1878',     weight = 1000,   type = 'weapon',      ammotype = 'AMMO_SHOTGUN',         image = 'weapon_shotgun02.png',      unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_SHOTGUN_SAWEDOFF',                 name = 'weapon_shotgun03',                     attachPoint = 9,    label = 'Hammerless Shotgun 1883',       weight = 1000,   type = 'weapon',      ammotype = 'AMMO_SHOTGUN',         image = 'weapon_shotgun03.png',      unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_SHOTGUN_SEMIAUTO',                 name = 'weapon_shotgun_semiauto',              attachPoint = 9,    label = 'Browning Auto-5',               weight = 1000,   type = 'weapon',      ammotype = 'AMMO_SHOTGUN',         image = 'weapon_shotgun06.png',      unique = true,   useable = true,   level = 0,     description = 'Placeholder' },

	-- Sniper Rifles
	{ model = 'WEAPON_SNIPERRIFLE_ROLLINGBLOCK',         name = 'weapon_sniperrifle_rollingblock',      attachPoint = 10,   label = 'Remington M1867',               weight = 1000,   type = 'weapon',      ammotype = 'AMMO_RIFLE',           image = 'weapon_sniper01.png',       unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC',  name = 'weapon_sniperrifle_rollingblock_exotic', attachPoint = 10, label = 'Steel Remington M1867',         weight = 1000,   type = 'weapon',      ammotype = 'AMMO_RIFLE',           image = 'weapon_sniper02.png',       unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_SNIPERRIFLE_CARCANO',              name = 'weapon_sniperrifle_carcano',           attachPoint = 10,   label = 'Carcano 1891 Short Rifle',      weight = 1000,   type = 'weapon',      ammotype = 'AMMO_RIFLE',           image = 'weapon_sniper03.png',       unique = true,   useable = true,   level = 0,     description = 'Placeholder' },

	-- Bows
	{ model = 'WEAPON_BOW',                              name = 'weapon_bow',                           attachPoint = 7,    label = 'Flatbow',                       weight = 100,    type = 'weapon',      ammotype = 'AMMO_ARROW',           image = 'weapon_bow01.png',          unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_BOW_IMPROVED',                     name = 'weapon_bow_improved',                  attachPoint = 7,    label = 'Sturdy Flatbow',                weight = 100,    type = 'weapon',      ammotype = 'AMMO_ARROW',           image = 'weapon_bow02.png',          unique = true,   useable = true,   level = 0,     description = 'Placeholder' },

	-- Throwable
	{ model = 'WEAPON_THROWN_DYNAMITE',                  name = 'weapon_thrown_dynamite',               attachPoint = 6,    label = 'Throwable Dynamite',            weight = 100,    type = 'weapon',      ammotype = nil,                    image = 'weapon_throw_dynamite.png', unique = false,  useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_THROWN_MOLOTOV',                   name = 'weapon_thrown_molotov',                attachPoint = 6,    label = 'Throwable Molotov',             weight = 100,    type = 'weapon',      ammotype = nil,                    image = 'weapon_throw_molotov.png',  unique = false,  useable = true,   level = 0,     description = 'Placeholder' },

	-- Melee
	{ model = 'WEAPON_MELEE_KNIFE',                      name = 'weapon_melee_knife',                   attachPoint = 4,    label = 'Knife',                         weight = 100,    type = 'weapon',      ammotype = nil,                    image = 'weapon_knife01.png',        unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_MELEE_HAMMER',                     name = 'weapon_melee_hammer',                  attachPoint = 13,   label = 'Hammer',                        weight = 100,    type = 'weapon',      ammotype = nil,                    image = 'weapon_hammer.png',         unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_MELEE_LANTERN',                    name = 'weapon_melee_lantern',                 attachPoint = 11,   label = 'Silver Lantern',                weight = 100,    type = 'weapon',      ammotype = nil,                    image = 'weapon_lantern01.png',      unique = true,   useable = true,   level = 0,     description = 'Placeholder' },
	{ model = 'WEAPON_MELEE_DAVY_LANTERN',               name = 'weapon_melee_davy_lantern',            attachPoint = 11,   label = 'Golden Lantern',                weight = 100,    type = 'weapon',      ammotype = nil,                    image = 'weapon_lantern02.png',      unique = true,   useable = true,   level = 0,     description = 'Placeholder' }

}
